<a href="https://colab.research.google.com/github/amruthaduvvuri/Cosine-Similarity-_Movie-Recommendation/blob/main/Cosine_Similarity_Movie_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Read Data

In [2]:
df = pd.read_csv("/content/movie_dataset.csv")

In [3]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton


generate features

In [4]:
features = ['keywords', 'cast', 'genres', 'director']

In [6]:
for feature in features:
  df[feature] = df[feature].fillna('')

In [9]:
def combined_features(row):
  return row['keywords']+" " +row['cast']+" "+row['genres']+" "+row['director']
df['combined_features'] = df.apply(combined_features,axis=1)

**Extracting Features**


sklearn.feature_extraction module can be used to extract features in format supported by machine learning algorithms


CountVectorizer()'s *fit_transform* will help to count the number of text

In [10]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_features'])
print("Count Matrix: ",count_matrix.toarray())

Count Matrix:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**Cosine Similarity**

In [12]:
cosine_sim = cosine_similarity(count_matrix)

In [16]:
movie_user_like ="Dead Poets Society"

def get_index_from(title):
  # Filter the DataFrame for the given title
  movie_row = df[df.title == title]
  # Check if the movie was found
  if not movie_row.empty:
    return movie_row["index"].values[0]
  else:
    # Handle the case where the movie is not found, e.g., print an error and return None
    print(f"Error: Movie '{title}' not found in the dataset.")
    return None

movie_index = get_index_from(movie_user_like)


In [17]:
similar_movies = list(enumerate(cosine_sim[movie_index]))

**Generating similar movies matrix**

In [18]:
print(similar_movies)

[(0, np.float64(0.0)), (1, np.float64(0.0)), (2, np.float64(0.0)), (3, np.float64(0.04499212706658475)), (4, np.float64(0.0)), (5, np.float64(0.0)), (6, np.float64(0.0)), (7, np.float64(0.04188539082916955)), (8, np.float64(0.0)), (9, np.float64(0.0)), (10, np.float64(0.0)), (11, np.float64(0.0)), (12, np.float64(0.0)), (13, np.float64(0.0)), (14, np.float64(0.0)), (15, np.float64(0.0)), (16, np.float64(0.041204282171516456)), (17, np.float64(0.0)), (18, np.float64(0.04188539082916955)), (19, np.float64(0.04891159880445184)), (20, np.float64(0.0)), (21, np.float64(0.0468292905790847)), (22, np.float64(0.05263157894736841)), (23, np.float64(0.0)), (24, np.float64(0.08111071056538126)), (25, np.float64(0.0512989176042577)), (26, np.float64(0.04335549847620599)), (27, np.float64(0.0468292905790847)), (28, np.float64(0.0)), (29, np.float64(0.0)), (30, np.float64(0.0)), (31, np.float64(0.04588314677411235)), (32, np.float64(0.0)), (33, np.float64(0.0)), (34, np.float64(0.0)), (35, np.float6

In [19]:
sorted_similar_movies = sorted(similar_movies, key = lambda x:x[1],reverse= True)

In [20]:
print(sorted_similar_movies)

[(2453, np.float64(0.9999999999999993)), (3250, np.float64(0.21677749238102995)), (905, np.float64(0.21052631578947364)), (2975, np.float64(0.2051956704170308)), (825, np.float64(0.19564639521780736)), (1507, np.float64(0.19134594929397594)), (4273, np.float64(0.1908854288927333)), (1774, np.float64(0.1873171623163388)), (4488, np.float64(0.18394180184548975)), (3526, np.float64(0.1835325870964494)), (1446, np.float64(0.179968508266339)), (1901, np.float64(0.17770466332772766)), (2764, np.float64(0.17770466332772766)), (3453, np.float64(0.17770466332772766)), (4754, np.float64(0.17770466332772766)), (2624, np.float64(0.17660431427533915)), (3616, np.float64(0.17342199390482396)), (990, np.float64(0.1675415633166782)), (1828, np.float64(0.16481712868606582)), (2227, np.float64(0.16222142113076254)), (3812, np.float64(0.16222142113076254)), (4045, np.float64(0.16222142113076254)), (747, np.float64(0.15789473684210523)), (1350, np.float64(0.15789473684210523)), (1600, np.float64(0.1578947

**Printing the Similar Movies**

In [21]:
def get_title_from_index(index):
  return df[df.index == index]["title"].values[0]

i = 0
for movies in sorted_similar_movies:
  print(get_title_from_index(movies[0]))
  i=i+1;
  if i>15:
    break

Dead Poets Society
Much Ado About Nothing
Patch Adams
Good Will Hunting
Flightplan
Alive
The Basket
What Just Happened
Adulterers
The Sting
The Tree of Life
The Greatest Game Ever Played
Light It Up
The Wood
The Naked Ape
Jakob the Liar
